### ISSUE TITLE
Getting Past git push heroku master

### ISSUE THREAD

**Issue by mgifford** [ofa/connect#19]
It's late, so I should look at this again with fresh eyes, but I can't seem to get past `git push heroku master`

There are a tonne of messages when I run this including:

remote:  !     Hello! It looks like your application is using an outdated version of Python.
remote:  !     This caused the security warning you saw above during the 'pip install' step.
remote:  !     We recommend 'python-2.7.11', which you can specify in a 'runtime.txt' file.
remote:  !       -- Much Love, Heroku.

So I upgraded python on my Mac. That wasn't the issue.

I tried using git pull

Then tried git  fetch & git --rebase

There are some errors that pop up, but...

remote:  !     Error while running '$ python manage.py collectstatic --noinput'
remote:        See traceback above for details.
remote: 
remote:        You may need to update application code to resolve this error.
remote:        Or, you can disable collectstatic for this application:
remote: 
remote:           $ heroku config:set DISABLE_COLLECTSTATIC=1
remote: 
remote:        https://devcenter.heroku.com/articles/django-assets
remote: 
remote:  !     Push rejected, failed to compile Multipack app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to oc-connect.
remote: 
To https://git.heroku.com/oc-connect.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/oc-connect.git'

This is where it dies.

Any idea what I am missing?

**Comment by nickcatal** [comment]
As mentioned in #20 this is fixed via `heroku config:set DISABLE_COLLECTSTATIC=1`

**Comment by mgifford** [comment]
Well that seemed to work nicely! Now I just have to get to the next stage now that I get that satisfying message `remote: Verifying deploy... done.`
